version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: scripts/Dockerfile-backend
    command: mvn spring-boot:run
    working_dir: /code
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./pan-pan-backend:/code

  front:
    container_name: front
    build:
      context: .
      dockerfile: scripts/Dockerfile-frontend
    working_dir: /code
    command: bash -c "npm install && npm start"
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./pan-pan-frontend:/code
      - /code/node_modules

  db:
    container_name: db
    build:
      context: .
      dockerfile: scripts/Dockerfile-database
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "spring"
      MYSQL_HOST: "db"
      MYSQL_USER: "spring"
      MYSQL_PASSWORD: "spring123"
      MYSQL_ROOT_PASSWORD: "root666"
    ports:
    - "3306"
